state_estimator:
  ros__parameters:
    # Fixed-lag smoother configuration
    optimization_frequency: 20.0
    transaction_timeout: 0.01
    lag_duration: 0.5

    motion_models:
      unicycle_motion_model:
        type: fuse_models::Unicycle2D

    unicycle_motion_model:
      #                         x      y      yaw    vx     vy     vyaw   ax   ay
      process_noise_diagonal: [0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.1, 0.1]

    sensor_models:
      initial_localization_sensor:
        type: fuse_models::Unicycle2DIgnition
        motion_models: [unicycle_motion_model]
        ignition: true
      odometry_sensor:
        type: fuse_models::Odometry2D
        motion_models: [unicycle_motion_model]
      imu_sensor:
        type: fuse_models::Imu2D
        motion_models: [unicycle_motion_model]

    initial_localization_sensor:
      publish_on_startup: true
      #                x      y      yaw    vx     vy     vyaw    ax     ay
      initial_state: [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]
      initial_sigma: [0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.100, 0.100]

    odometry_sensor:
      topic: 'odom'
      twist_target_frame: 'base_footprint'
      linear_velocity_dimensions: ['x', 'y']
      angular_velocity_dimensions: ['yaw']

    imu_sensor:
      topic: 'imu'
      twist_target_frame: 'base_footprint'
      angular_velocity_dimensions: ['yaw']

    publishers:
      filtered_publisher:
        type: fuse_models::Odometry2DPublisher

    filtered_publisher:
      topic: 'odom_filtered'
      base_link_frame_id: 'base_footprint'
      odom_frame_id: 'odom'
      map_frame_id: 'map'
      world_frame_id: 'odom'
      publish_tf: true
      publish_frequency: 10.0
