name: CI

on:
  push:
    branches:
      - '*'

jobs:
  ci:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            distro: humble
          - os: ubuntu-22.04
            distro: iron
          - os: ubuntu-22.04
            distro: rolling
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: ros-tooling/setup-ros@0.7.0
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - run: sudo apt remove python3-openssl -y
      - uses: ros-tooling/action-ros-ci@0.3.5
        with:
          target-ros2-distro: ${{ matrix.distro }}
